### ISSUE TITLE
Reading from string

### ISSUE THREAD

**Issue by TrySound** [mcasimir/gulp-rollup#13]
This will make plugin more gulpy
https://github.com/rollup/rollup/issues/272

**Comment by TrySound** [comment]
This too :)
https://github.com/TrySound/rollup-plugin-memory

**Comment by Permutatrix** [comment]
This would require a major change to how the plugin works, and it isn't needed in most cases, so it would be best to keep the current functionality as an option. I think it would be best to make a separate plugin, maybe called gulp-rollup-buffers, for this.

As I said in the PR, I have no time at the moment; I'm typing this on my phone. Otherwise I'd get started right away.

**Comment by TrySound** [comment]
@Permutatrix Do you know that you did the same thing like gulp-browserify?
