### ISSUE TITLE
allow usage after sourceMaps.init()

### ISSUE THREAD

**Issue by flying-sheep** [mcasimir/gulp-rollup#19]
i saw what you said in https://github.com/mcasimir/gulp-rollup/pull/12#issuecomment-155910048, but maybe there’s a way to do:

```js
gulp.src('src/js/main.js')
	.pipe(sourcemaps.init())
	.pipe(rollup())
	.pipe(uglify())
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('js/'))
```

i didn’t specify `sourceMaps: true` since there’s a way for plugins to be sourcemaps-aware aka detect it from the stream.

**Comment by Permutatrix** [comment]
Well, yes, but that would require telling gulp.src to read the file into memory, and Rollup does that itself, so it's redundant. There's a lot of weird stuff and shades of grey when it comes to this plugin because [its very premise is flawed](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156866698).

**Comment by flying-sheep** [comment]
maybe we could change this to work something like explained here https://github.com/gulpjs/plugins/issues/205#issuecomment-166554047:


>```js
>rollup.src('src/js/main.js')  //returns stream of all used files…
>	.pipe(plumber())            //…including dependency metadata
>	.pipe(sourcemaps.init())
>	.pipe(rollup.bundle())
>		.pipe(uglify())
>	.pipe(sourcemaps.write('.'))
>	.pipe(gulp.dest('js/'))
>```

**Comment by Permutatrix** [comment]
@flying-sheep For the record: I think that's a wonderful idea, as I say in [this comment.](https://github.com/gulpjs/plugins/issues/205#issuecomment-166559966)

**Comment by Permutatrix** [comment]
Fixed with v2.
