### ISSUE TITLE
Imports without .js are not being found in the hypothetical file system

### ISSUE THREAD

**Issue by rberner** [mcasimir/gulp-rollup#39]
First off, I'm using gulp-rollup instead of rollup-stream because I have to dynamically modify the contents of the files before I allow them to be bundled. I think that's a valid reason to need it over rollup-steam, but I'm open to other ideas.

I noticed that when I specify an entry point that uses imports in the following format:

`import utils from './utils'`

I get an error: "/src/utils does not exist in the hypothetical file system!"

To solve this, I had to add the .js extension to every one of my imports:

`import utils from './utils.js'`

Is this proper behavior? I would think gulp-rollup would search for imports in the hypothetical file system without matching extension.

**Comment by Permutatrix** [comment]
gulp-rollup 2.3.0 now adds a .js extension if necessary by default. This can be customized using `options.impliedExtensions`.

If you just need to transform the files before sending them to Rollup, there's probably a [Rollup plugin](https://github.com/rollup/rollup/wiki/Plugins) that will do what you want. If there isn't, you can write your own or give [rollup-plugin-gulp](https://www.npmjs.com/package/rollup-plugin-gulp) a try&mdash;and tell me how it goes, because I still haven't gotten around to checking if that plugin even works.
