### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by mabar** [mcasimir/gulp-rollup#47]
Is there a way how to use rollup cache as described [here?](https://github.com/rollup/rollup/wiki/JavaScript-API)
Files are with file watcher bundled every time, so this can ben significant speed up.

**Comment by Permutatrix** [comment]
I suppose I could do the same thing I did with rollup-stream: [add a 'bundle' method](https://github.com/Permutatrix/rollup-stream#usage-with-caching). I need to sleep, though, so maybe that's a terrible idea, but I can't imagine why right now.

I hope you've considered just using rollup-stream instead of gulp-rollup, though. The vast majority of people using gulp-rollup would be better off using rollup-stream instead, and it already has this feature.

**Comment by Permutatrix** [comment]
You seem to need multiple entry points, of course, [which is possible with rollup-stream](https://github.com/Permutatrix/rollup-stream/issues/9). That should probably be in the README.

**Comment by MasterOfZozo** [comment]
It would be better to have bundle method in gulp-rollup as api is much easier to use.

**Comment by Permutatrix** [comment]
@MasterOfZozo The difference in usability isn't as big as it looks, but okay, I'll probably add it tomorrow.

**Comment by iainvdw** [comment]
I've started used gulp-rollup as well and wanted this exact feature to speed up the bundling process.  via the caching mechanism of Rollup. However, after looking into the code, adding caching would seem a bit more complex than just adding a 'bundle' event and exposing the result. This is because this plugin is able to handle multiple entries and each bundle should have a separate cache variable. Variables aren't able to be stored in the plugin itself, as each time the plugin runs a new instance is created.

But I believe this _can_ be achieved by exposing the name of the entry file for the bundle as a key for a cache object, in which the cache for each bundle is stored in and retrieved from by this key. 

@Permutatrix Would this be possible by exposing a similar event like rollup-stream with the addition of the name of the entry in the event handler function?

**Comment by Permutatrix** [comment]
Alright, I've finally added functionality for this in v2.11.0. Have a look at [`options.separateCaches`](https://github.com/mcasimir/gulp-rollup/tree/997cd454df5ad34ebfcb4d2f8fce28f00b200127#optionsseparatecaches) and [`options.generateUnifiedCache`](https://github.com/mcasimir/gulp-rollup/tree/997cd454df5ad34ebfcb4d2f8fce28f00b200127#optionsgenerateunifiedcache) in the README.
